-- 코드를 입력하세요
SELECT a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, SUM(s.SALES * a.PRICE) as TOTAL_SALES
FROM BOOK_SALES as s
JOIN BOOK as a
on s.BOOK_ID = a.BOOK_ID
JOIN AUTHOR as b
on a.AUTHOR_ID = b.AUTHOR_ID
WHERE YEAR(s.SALES_DATE) = 2022 and MONTH(s.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, a.CATEGORY
ORDER BY a.AUTHOR_ID, a.CATEGORY desc