SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO AS i
JOIN ITEM_TREE AS t
ON i.ITEM_ID = t.ITEM_ID
WHERE 1 = 1
AND t.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
    GROUP BY PARENT_ITEM_ID
)
ORDER BY i.ITEM_ID DESC
;