-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, sum(p.PRICE * o.SALES_AMOUNT) as SALES
FROM PRODUCT as p
JOIN (SELECT PRODUCT_ID, SALES_AMOUNT FROM OFFLINE_SALE) as o
on p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES desc, p.PRODUCT_CODE;
