-- 코드를 입력하세요
SELECT a.USER_ID, a.NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) as "전체주소", CONCAT(LEFT(TLNO, 3), "-", MID(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) as "전화번호"
FROM USED_GOODS_USER as a
JOIN USED_GOODS_BOARD as b
ON a.USER_ID = b.WRITER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY a.USER_ID desc