-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, b.GENDER, COUNT(DISTINCT a.USER_ID) as USERS
FROM ONLINE_SALE as a
JOIN USER_INFO as b
ON a.USER_ID = b.USER_ID
WHERE GENDER is not NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER