-- 코드를 입력하세요
SELECT b.PRODUCT_ID, b.PRODUCT_NAME, SUM(a.AMOUNT * b.PRICE) as TOTAL_SALES
FROM FOOD_ORDER as a
JOIN FOOD_PRODUCT as b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE a.PRODUCE_DATE like '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID