-- 코드를 입력하세요
SELECT J.FLAVOR
FROM FIRST_HALF as H
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) as J
ON H.FLAVOR = J.FLAVOR
ORDER BY (J.TOTAL_ORDER + H.TOTAL_ORDER) desc
LIMIT 3