-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, sum(b.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as b
join USED_GOODS_USER as u
on b.WRITER_ID = u.USER_ID
WHERE STATUS = "DONE"
GROUP BY u.USER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY TOTAL_SALES