SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS u
JOIN USED_GOODS_BOARD AS b
ON u.USER_ID = b.WRITER_ID
WHERE b.STATUS LIKE '%DONE%'
GROUP BY u.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
;