SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES AS e
JOIN HR_GRADE AS g
ON e.EMP_NO = g.EMP_NO
JOIN HR_DEPARTMENT AS d
ON e.DEPT_ID = d.DEPT_ID
WHERE g.YEAR = '2022'
GROUP BY e.EMP_NO
ORDER BY SUM(g.SCORE) DESC
LIMIT 1
;