SELECT A.GRADE, A.ID, A.EMAIL
FROM (
    SELECT A.ID,
           CASE WHEN SUM(CASE WHEN B.NAME='Python' THEN 3
                              WHEN B.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 3 THEN 'A'
                WHEN SUM(CASE WHEN B.NAME='C#' THEN 1 ELSE 0 END) > 0 THEN 'B'
                WHEN SUM(CASE WHEN B.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 THEN 'C'
                ELSE NULL END AS GRADE,
                MIN(A.EMAIL) AS EMAIL
    FROM DEVELOPERS A
    INNER JOIN SKILLCODES B ON A.SKILL_CODE & B.CODE = B.CODE
    GROUP BY A.ID
) AS A
WHERE A.GRADE IS NOT NULL
ORDER BY A.GRADE, A.ID;